# Generated by Django 5.1.3 on 2024-11-26 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_obtainedbadge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='user',
        ),
        migrations.AddField(
            model_name='badge',
            name='condition_type',
            field=models.CharField(choices=[('reviews', 'Number of Reviews'), ('likes given', 'Number of Likes Given'), ('likes received', 'Number of Likes Received'), ('dislikes given', 'Number of Dislikes Given'), ('dislikes received', 'Number of Dislikes Received')], default='condition', max_length=30),
        ),
        migrations.AddField(
            model_name='badge',
            name='threshold',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='obtainedbadge',
            unique_together={('badge_obtained', 'user')},
        ),
    ]
