# Generated by Django 5.1.3 on 2024-11-26 01:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_badge_user_badge_condition_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='condition_type',
            field=models.CharField(choices=[('reviews', 'Number of Reviews'), ('likes given', 'Number of Likes Given'), ('likes received', 'Number of Likes Received'), ('dislikes given', 'Number of Dislikes Given'), ('dislikes received', 'Number of Dislikes Received')], max_length=30),
        ),
    ]
