# Generated by Django 5.1.3 on 2024-12-09 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userreview_created_at_alter_badge_condition_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='obtainedbadge',
            name='badge_obtained',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.badge'),
        ),
        migrations.AlterField(
            model_name='obtainedbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
