# Generated by Django 5.1.3 on 2024-12-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_obtainedbadge_badge_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='book',
            field=models.CharField(default='', max_length=100),
        ),
    ]
